name: Athena CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build the Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        tags: my-electron-app:latest

    - name: Run the tests
      uses: docker://my-electron-app:latest